### ISSUE TITLE
iteminfo have errors:

### ISSUE THREAD

**Issue by darknessfmy** [zackdreaver/ROenglishRE#13]
have very much error in the file.

Example line 19556
![image](https://cloud.githubusercontent.com/assets/7623682/21598204/0bab1caa-d137-11e6-9565-e6eb039644fe.png)

**Comment by zackdreaver** [comment]
Does this affect your client, like crashing or the description isn't read properly?

**Comment by hurtsky** [comment]
i also have this problem, after merging the last commit that you merge with JRO item i think.. but i fix this manually by adding all  < " >, @zackdreaver yup, it does give error at client

**Comment by hurtsky** [comment]
just a suggestion @zackdreaver , i think you should try use sever database editor, it will make your live easier :+1: 
https://rathena.org/board/files/file/3269-server-database-editor/

**Comment by zackdreaver** [comment]
Well I have no problem so far like what you guys have here.
I only set my text editor, which ever it is, to ANSI encoding.
I see from your screen shot that you're not using this encoding.

**Comment by zackdreaver** [comment]
Here is mine from notepad++ with ANSI encoding
![new picture](https://cloud.githubusercontent.com/assets/10024221/21601410/f9b46c8c-d1bc-11e6-8734-b2d8e4219702.jpg)
This item using two languages Korean and Japan.

![new picture 1](https://cloud.githubusercontent.com/assets/10024221/21601453/8ee7030a-d1bd-11e6-8841-2eebb54abf91.jpg)
And this item using two languages Korean and Chinese.

**Comment by hurtsky** [comment]
Here mine, using ANSI also, i also keep having conflict during cherry-pick even my repo is same as you (not modified one)

![capture](https://cloud.githubusercontent.com/assets/4039059/21668762/decadada-d33f-11e6-9335-f0c7f8dc5df3.PNG)

**Comment by zackdreaver** [comment]
1.What's your OS main language?
2.What's your git client?
3.Can you check your default git client encoding?

**Comment by hurtsky** [comment]
im pretty sure all git default at UTF-8,
and my OS main language is english, not adding any others language here. from what i can see right now, from git diff, 
```File is considered as binary: invalid character 0x00 in line 14778, at position 7```
there some  Japanese words is using invalid character, which make those error. maybe due to copy paste thing?, because before you're merged with jro, no issues in cherry-picking.

**Comment by zackdreaver** [comment]
The git encoding for this project is cp1252.

**Comment by hurtsky** [comment]
@zackdreaver okay thanks, will try set encoding to cp1252

**Comment by zackdreaver** [comment]
Closing this, because it was GIT client's issue.

**Comment by hurtsky** [comment]
@zackdreaver sorry for reply at this issue again, but i still having problem after changing the encoding to cp1252, its like the git change the encoding after git checkout.. if possible, can you not adding non translated (japanese) into git? i means, to avoid errors.. will appreciate any of your respond, just a request.

**Comment by zackdreaver** [comment]
Going backwards is not my style when working on something.

You can always use the pre-merge one here
39c248b37ade9c818e666c7394bf955050273b67

**Comment by hurtsky** [comment]
it's okay, it just a request, i know i can always use the pre-merge. thank you

**Comment by zackdreaver** [comment]
@hurtsky
try to update, I have pushed a workaround though don't know if it works or not.
https://github.com/zackdreaver/ROenglishRE/commit/e849392840bc600ed135fcf94cc90a48f79f3cf3

**Comment by hurtsky** [comment]
@zackdreaver thanks, i will test it let you know.. i think i'm wrongly explain the last comment, its not , not adding the japanese word, but replace the japanese word with "????" something like that, because from what i saw, the git change the encoding after -git checkout because they detect invalid character.. but let me test first the one you recommend. and will let you know again. thanks again

**Comment by hurtsky** [comment]
@zackdreaver looks like it same sir, have error at the same line, actually i'm not really bothered with this, i can just fix it with a few commands but the others of your users might not know.. At yours local repo its already okay but after you do git checkout, the git change its encoding because invalid character i get this when using git diff (invalid character 0x00), thus make your users error.. my idea is create another branch (-pretranslate) that have non translated japanese word, and the (master) branch replace the japanese word with "????". and only merge the japanese word to master after it been translated. im pretty sure your work/repo have many user/follower, just like myself, i always keep my repo update with yours :+1: 

thanks again

**Comment by zackdreaver** [comment]
Try download this one.
[itemInfo.zip](https://github.com/zackdreaver/ROenglishRE/files/721488/itemInfo.zip)

**Comment by hurtsky** [comment]
no errors in that itemInfo @zackdreaver , looks good

**Comment by zackdreaver** [comment]
Ok then, that explain it's GIT client's fault.
Fill fix related issue, maybe in 1 or 2 weeks.

**Comment by hurtsky** [comment]
thanks :+1:
