### ISSUE TITLE
[20285] Costume Blowing Scattered Sakura

### ISSUE THREAD

**Issue by exneval** [zackdreaver/ROenglishRE#9]
The view ID of this item is 1331, and this is supposed to be animation headgear like Moonstar, Superstar,
The problem is, in status window and char selection, this item will displaying [19023] Queen Scaraba Crown, view ID 1231, maybe there's something wrong with sprite? Because 1231 and 1331 is quite similar

**Comment by zackdreaver** [comment]
It's more like server problem instead of client.
Adding view id to itemInfo means nothing to current emulator, maybe it will affect aegis but not rA or other similiar emulator. It should be 0 for view id, I remember adding that one from jRO which is has no itemInfo implementation.

So the fix is, check the item_db.txt and set the viewID to 0 for that item.

**Comment by exneval** [comment]
Ah yes, maybe all hat with animation should set view id to 0

**Comment by zackdreaver** [comment]
Yes, it should be 0 view if it uses special "treatment" to display it's effect.
Closing this.
